# Generated by Django 5.2.3 on 2026-08-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_notification_savedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', max_length=20),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
