# Generated by Django 5.2.3 on 2026-08-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.TextField(blank=True),
        ),
    ]
