# Generated by Django 5.2.3 on 2026-08-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
